### ISSUE TITLE
Extending Limelight to work with general Valve Steam streaming and not only the Nvidia Windows solution?

### ISSUE THREAD

**Issue by poVoq** [moonlight-stream/moonlight-common#10]
Would be great if there was an attempt to extend Limelight to work with general Valve Steam streaming and not only the Nvidia Windows solution.

Maybe Valve will even pick it up as the official thin & non-x86 client given their positive stance to open-source?

**Comment by Shyran** [comment]
Even if the streaming protocols are similar, Steam's In-Home Streaming requires the client to be logged in to Steam as well as the host, so that would need to be implemented and it may not be feasible depending on how Steam implements their authentication and whether it's available to 3rd party developers to work with. If the client authentication could be implemented and the streaming protocols were similar enough, I could see that being a fork of Limelight and not necessarily something baked in.

**Comment by gu3st** [comment]
From experience, it's easy to login to Steam from a non-real steam device. There's libraries out there for NodeJS, C# and other languages that are designed for that. node-steam is one example.

**Comment by Shyran** [comment]
Thanks for the info. Then I think it'd come down to how similar the streaming protocols are.

**Comment by maxpiva** [comment]
What about extending the functionality to other protocols like. Playstation Remote Play, and the XBOX One Windows 10 Streaming.

**Comment by poVoq** [comment]
@Shyran: I think Valve originally collaborated with Nvidia to implement this, thus it is likely that the protocol is very similar. However since they want to sell their own streaming box they might not be willing to share the protocol specifications for now.

**Comment by gu3st** [comment]
Well, all Valve's stuff is implemented in protobuf, and the protobufs for their streaming client are available (as people dump all Valve's protobufs for all their games).

It's possible, just takes an interested and motivated party to do it.  I am not skilled enough in the required languages to do this.

**Comment by mrb113** [comment]
As mentioned, Moonlight is just an open-source implementation of the NVIDIA Gamestream protocol. We're not planning on doing anything Valve-specific right now.
